import { StyleSheet, Dimensions } from 'react-native';
import { fontStyles } from '../../utils/fontStyles';
const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  input: {
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    marginBottom: 12,
    backgroundColor: '#fafafa',
    textAlign: 'right',
    color: '#222',
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  container: {
    paddingBottom: 20,
    backgroundColor: '#f8f8f8',
  },
  mainImage: {
    width: width,
    height: 350,
    backgroundColor: '#e9e9e9',
  },
  thumbnailList: {
    marginTop: 10,
  },
  thumbnailListContainer: {
    paddingHorizontal: 10,
  },
  thumbnail: {
    width: 60,
    height: 60,
    borderRadius: 10,
    marginHorizontal: 5,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  selectedThumbnail: {
    borderColor: '#8B7355',
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    backgroundColor: '#fff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: 20, // Adjusted from -40 to give space for thumbnails
    paddingBottom: 20,
  },
  productName: {
    fontSize: 28, // Reduced size for better balance
    color: '#333',
    marginBottom: 8,
    textAlign: 'right',
    fontFamily: fontStyles.DGAgnadeenRegular, // Kept the new font
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  price: {
    fontSize: 24,
    color: '#8B7355',
    fontFamily: fontStyles.PoppinsBold, // Kept Poppins for numbers
  },
  status: {
    fontSize: 14,
    paddingHorizontal: 16,
    paddingVertical: 5,
    borderRadius: 20,
    overflow: 'hidden',
    fontWeight: 'bold',
    fontFamily: fontStyles.PoppinsBold,
  },
  available: {
    backgroundColor: 'rgba(58, 125, 68, 0.1)',
    color: '#3A7D44',
  },
  notAvailable: {
    backgroundColor: 'rgba(183, 28, 28, 0.1)',
    color: '#B71C1C',
  },
  categoryContainer: {
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  category: {
    fontSize: 14,
    color: '#8B7355',
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  createdBy: {
    fontSize: 15,
    color: '#C4A484',
    fontWeight: 'bold',
    fontFamily: fontStyles.PoppinsBold,
  },
  description: {
    fontSize: 16,
    color: '#555',
    marginVertical: 20,
    textAlign: 'right',
    lineHeight: 26,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  sizesContainer: {
    marginVertical: 10,
  },
  sizesLabel: {
    fontSize: 16,
    color: '#333',
    marginBottom: 12,
    fontWeight: 'bold',
    textAlign: 'right',
    fontFamily: fontStyles.PoppinsBold,
  },
  sizesRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 12,
  },
  sizeBtn: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#fff',
  },
  sizeBtnSelected: {
    backgroundColor: '#8B7355',
    borderColor: '#8B7355',
  },
  sizeText: {
    color: '#8B7355',
    fontWeight: 'bold',
    fontSize: 15,
    fontFamily: fontStyles.PoppinsBold,
  },
  sizeTextSelected: {
    color: '#fff',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#f0f0f0',
    gap: 16,
  },
  buyButton: {
    flex: 1,
    backgroundColor: '#8B7355',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 2,
  },
  sellButton: {
    flex: 1,
    backgroundColor: '#5C4630',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    elevation: 2,
  },
  loginButton: {
    backgroundColor: '#8B7355',
    borderRadius: 12,
    paddingVertical: 18,
    alignItems: 'center',
    margin: 20,
    elevation: 2,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18, // Adjusted size for buttons
    fontFamily: fontStyles.DGAgnadeenRegular, // Kept the new font
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.13,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 3 },
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#8B7355',
    textAlign: 'center',
    marginBottom: 18,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  countryList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 12,
    gap: 8,
  },
  countryButton: {
    backgroundColor: '#F3F3F3',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    margin: 3,
    borderWidth: 1,
    borderColor: '#eee',
  },
  countryButtonText: {
    color: '#8B7355',
    fontFamily: fontStyles.DGAgnadeenRegular,
    fontSize: 13,
  },
  selectedCountryButton: {
    backgroundColor: '#8B7355',
    borderColor: '#8B7355',
  },
  selectedCountryButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  modalButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 18,
    gap: 10,
  },
  modalButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
    marginHorizontal: 2,
  },
  sendButton: {
    backgroundColor: '#5C4630',
    paddingVertical: 9,
  },
  cancelButton: {
    backgroundColor: '#eee',
  },
  cancelButtonText: {
    color: '#8B7355',
    fontWeight: 'bold',
  },
  disabledButton: {
    opacity: 0.6,
  },
  priceBookmark: {
    position: 'absolute',
    left: -18,
    top: 0,
    backgroundColor: '#8B7355',
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    paddingLeft: 38,
    paddingRight: 18,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
    marginTop: 0,
    elevation: 2,
    shadowColor: '#C4A484',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 4,
    zIndex: 10,
  },
  priceBookmarkText: {
    color: '#fff',
    fontSize: 20,
    fontFamily: fontStyles.PoppinsBold,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  categoryBadge: {
    backgroundColor: '#F3F3F3',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-end',
    marginRight: 0,
    marginLeft: 8,
    minWidth: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EED9B6',
  },
  categoryBadgeText: {
    color: '#8B7355',
    fontFamily: fontStyles.DGAgnadeenRegular,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

export default styles;
