import { StyleSheet } from 'react-native';
import { colors } from '../../utils';
import { fontStyles } from '../../utils/fontStyles';

// ألوان pastel عصرية
const pastelBlue = '#E3F0FF';
const pastelGreen = '#E6F9EA';
const pastelPink = '#FFE6F0';
const pastelYellow = '#FFF9E3';
const pastelGray = '#F7F8FA';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundGray, // لون خلفية هادئ
    paddingTop: 0,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.backgroundGray,
  },
  header: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  backButton: {
    padding: 6,
    backgroundColor: colors.whiteColor,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EEE',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: fontStyles.DGAgnadeenRegular,
    letterSpacing: 0.5,
    color: colors.whiteColor,
  },
  headerRightPlaceholder: {
    width: 24,
  },
  listContentContainer: {
    paddingBottom: 30,
    paddingTop: 10,
  },
  summarySection: {
    marginBottom: 18,
    paddingHorizontal: 10,
  },
  totalProfitContainer: {
    backgroundColor: '#F7FFF9',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 10,
    marginBottom: 18,
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#8CB65E',
    width: '100%',
    minHeight: 54,
    elevation: 2,
    shadowColor: '#8CB65E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    flexDirection: 'row',
  },
  totalProfitText: {
    fontSize: 17,
    fontWeight: 'bold',
    color: colors.greenColor,
    fontFamily: fontStyles.DGAgnadeenRegular,
    marginTop: 6,
  },
  totalProfitIconCircle: {
    backgroundColor: '#E6F9EA',
    borderRadius: 32,
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  summaryCardsContainer: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginBottom: 6,
    gap: 16,
  },
  card: {
    backgroundColor: colors.whiteColor,
    borderRadius: 14,
    paddingVertical: 0,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    width: '100%',
    marginHorizontal: 0,
    marginBottom: 2,
    minHeight: 40,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    flexDirection: 'row',
  },
  cardIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 6,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: fontStyles.DGAgnadeenRegular,
    color: colors.fontSecondColor,
  },
  cardValue: {
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: fontStyles.DGAgnadeenRegular,
    color: colors.primary,
  },
  percentageText: {
    fontSize: 14,
    marginTop: 4,
    fontFamily: fontStyles.DGAgnadeenRegular,
    color: colors.greenColor,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 4,
    marginTop: 2,
    textAlign: 'right',
    color: colors.fontMainColor,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  orderItem: {
    backgroundColor: '#FAFAFA',
    borderRadius: 10,
    marginHorizontal: 4,
    marginVertical: 6,
    padding: 12,
    flexDirection: 'column',
    borderBottomWidth: 1,
    borderBottomColor: '#ECECEC',
  },
  orderHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  orderId: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary,
    fontFamily: fontStyles.DGAgnadeenRegular,
    textAlign: 'left',
  },
  orderDate: {
    fontSize: 15,
    color: colors.grayText,
    fontFamily: fontStyles.DGAgnadeenRegular,
    textAlign: 'right',
  },
  orderBody: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  orderProfitContainer: {
    alignItems: 'flex-end',
  },
  orderLabel: {
    fontSize: 15,
    color: colors.grayText,
    marginBottom: 2,
    textAlign: 'right',
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  orderValue: {
    fontSize: 19,
    fontWeight: 'bold',
    color: colors.greenColor,
    fontFamily: fontStyles.DGAgnadeenRegular,
    textAlign: 'right',
  },
  profitBadge: {
    backgroundColor: pastelGreen,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  profitBadgeText: {
    color: colors.greenColor,
    fontWeight: 'bold',
    fontSize: 14,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  statusContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 16,
    borderRadius: 24,
    minWidth: 110,
    justifyContent: 'center',
    marginTop: 2,
  },
  statusIcon: {
    marginRight: 6,
  },
  statusText: {
    fontSize: 15,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 60,
    paddingHorizontal: 20,
  },
  emptyText: {
    fontSize: 19,
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 20,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  refreshEmptyButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    marginTop: 10,
    elevation: 2,
  },
  refreshEmptyButtonText: {
    color: colors.whiteColor,
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  errorText: {
    fontSize: 17,
    color: colors.errorColor,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  retryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 13,
    paddingHorizontal: 28,
    borderRadius: 10,
    elevation: 2,
  },
  retryButtonText: {
    color: colors.whiteColor,
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  // زر طلبات السحب العصري
  withdrawalButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 10,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    marginHorizontal: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 2,
  },
  withdrawalButtonText: {
    color: colors.whiteColor,
    fontWeight: 'bold',
    fontSize: 16,
    fontFamily: fontStyles.DGAgnadeenRegular,
    marginLeft: 8,
  },
  withdrawalIconCircle: {
    backgroundColor: 'transparent',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '96%',
    maxHeight: '88%',
    backgroundColor: colors.whiteColor,
    borderRadius: 14,
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.13,
    shadowRadius: 7,
  },
  modalHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    backgroundColor: colors.primary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  modalTitle: {
    fontSize: 21,
    fontWeight: 'bold',
    color: colors.whiteColor,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  closeButton: {
    padding: 8,
    backgroundColor: colors.whiteColor,
    borderRadius: 20,
    elevation: 3,
  },
  modalBody: {
    padding: 12,
  },
  detailRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F2',
    paddingVertical: 8,
  },
  detailIcon: {
    marginRight: 10,
  },
  detailLabel: {
    fontSize: 14,
    color: colors.fontSecondColor,
    fontFamily: fontStyles.DGAgnadeenRegular,
    textAlign: 'right',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.fontMainColor,
    fontFamily: fontStyles.DGAgnadeenRegular,
    textAlign: 'left',
  },
  cancellationSection: {
    marginTop: 28,
    padding: 14,
    backgroundColor: '#FFF0F0',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FF5C5C',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  
  cancellationIcon: {
    marginRight: 10,
  },
  cancellationTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.errorColor,
    marginBottom: 0,
    fontFamily: fontStyles.DGAgnadeenRegular,
  },
  cancellationReason: {
    fontSize: 17,
    color: colors.blackText,
    fontFamily: fontStyles.DGAgnadeenRegular,
    textAlign: 'left',
  },
  ordersContainer: {
    paddingHorizontal: 4,
    paddingBottom: 12,
  },
  cardDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 10,
    alignSelf: 'center',
  },
});

export default styles;